export type APIS = "/auth/login" | "/users/add" | "/products" |"/login" | '/signup' | '/sendOtp'| '/verifyOtp'
export const GHR_KA_URL='192.168.1.11'
export const CODEBREW_KA_URL='192.168.100.105'
export const LOGIN='/login'
export const SIGNUP='/signup'
export const SEND_OTP='/sendOtp'
export const VERIFY_OTP='/verifyOtp'
